### ISSUE TITLE
Why are we in this bubble

### ISSUE THREAD

**Issue by xunzijian1158** [qiufei/banking#12]
Clearly we have more convenient moodle platform, why did foreign website Posting?

**Comment by qiufei** [comment]
@xunzijian1158 

感谢你的建议，我当初选择在这个平台讨论，是觉得这个网站移动端的显示支持较好，所以大家方便随时在手机上查看、回复、讨论。

既然你比较喜欢moodle平台，我想应该也有人跟你有同样的想法，所以我也把这四个讨论题目放到moodle平台这门课程的新闻公告区了，你们也可以到moodle平台讨论。
